"""Initial async models migration

Revision ID: ae2ba43b70be
Revises: 
Create Date: 2026-03-16 07:16:28.772829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae2ba43b70be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('persona_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memories_id'), 'agent_memories', ['id'], unique=False)
    op.create_index(op.f('ix_agent_memories_persona_id'), 'agent_memories', ['persona_id'], unique=False)
    op.create_table('general_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_general_data_id'), 'general_data', ['id'], unique=False)
    op.create_index(op.f('ix_general_data_title'), 'general_data', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_general_data_title'), table_name='general_data')
    op.drop_index(op.f('ix_general_data_id'), table_name='general_data')
    op.drop_table('general_data')
    op.drop_index(op.f('ix_agent_memories_persona_id'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_id'), table_name='agent_memories')
    op.drop_table('agent_memories')
    # ### end Alembic commands ###
